### ISSUE TITLE
[Feature Request] PhpStorm Debug Documentation

### ISSUE THREAD

**Issue by deviantpixel** [forumone/web-starter#108]
It would be really helpful to have PhpStorm debug documentation about how to debug this site or other Drupal sites in general using PhpStorm.

I know there have been links floating around but any in particular that have worked fairly well and been helpful?

Thanks

**Comment by windycitymoon** [comment]
+1

On Wednesday, August 12, 2015, Keenan Holloway notifications@github.com
wrote:

> It would be really helpful to have PhpStorm debug documentation about how
> to debug this site or other Drupal sites in general using PhpStorm.
> 
> I know there have been links floating around but any in particular that
> have worked fairly well and been helpful?
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/forumone/web-starter/issues/108.

## 

-- Sent from Mobile

**Comment by ohthehugemanatee** [comment]
Here's how you do it on one of our web-starter environments. I'm saving
this as a blog post, btw. (stern looks all around)

1) Tell PHPStorm to listen for incoming xdebug connections by clicking the
little telephone icon in the top right corner.  It turns green.

​
2) Mark a line as a "break point" by clicking beside the line number, to
add a red dot. This is where PHPStorm will pause execution.

3) In any web browser, visit a page on your local dev environment that
should go past that break point. (actually that example is a bad one
because it's a drush command) Add the parameter
?XDEBUG_SESSION_START=cam_is_muscular to the end of your URL. The value can
really be anything, but that value in particular makes it better.

That's it! The page will stay "loading" and PHPStorm will steal focus from
the browser to show you the debugger on that line. Below the code, you'll
see the "debug pane", which shows all the variables in the environment as
of that line. You can click into arrays and objects to see the value of
everything you have available, even globals like $_GET!  On the left of the
variables is a backtrace of "how it got here". You can click up to each
level and see the current environment there, too.

​
You can use the pointy-clicky icons if you like, but you'll be stronger,
healthier, happier, and more successful in life if you use the keyboard
shortcuts:

_F8: Step over: *Go to the next line and pause there.
*F7: Step into: *There's a function in the currently highlighted line. Step
"into" that function and pause on the first line. If there are multiple
functions, it will go through them one at a time.
*shift+F7: Smart step into: *(PHPStorm 7 and up) like "step into", but
offers you a choice of which function to step into on a line with multiple
functions.
*alt+F8: Evaluate expression: *Run some arbitrary code in the middle of
execution. Find out what happens when you unset($_GET) partway through a
request!
*alt+F9: Run to cursor: *Run normally until wherever your cursor is
situated.
*cmd+alt+R: Resume:_ Resume running until you find another breakpoint, if
any.

_NOTES AND TROUBLESHOOTING_

_Is there an easier way to start a debug session?_
Why, yes! I'm glad you asked. Xdebug can also be triggered from a browser
cookie. There are a ton of browser plugins that make it very convenient to
trigger xdebug this way. I use The Easiest XDebug
https://addons.mozilla.org/en-US/firefox/addon/the-easiest-xdebug/ for
Firefox, but find one you like! Not that older versions of web-starter have
a varnish configuration that filters out the Xdebug cookie, so either
update web-starter or access your site directly through NGINX at
http://localhost:8081/ .

_I'm getting weird errors about being unable to find a local path to
somethingorother. What do I do?_
The three things needed to get Xdebug working are: the browser has to
trigger the server to start a connection, something needs to be listening
for that connection, and it has to be able to relate paths on the server to
paths on its' local copy. This is a problem with that third step. PHPStorm
is getting a message like "I'm running /vagrant/public/index.php now, what
line do you want me to stop on?" But it doesn't know where that is on your
computer. You have to set up a mapping between paths on the vagrant box and
paths on your own computer.

The error message in PHPStorm 9 links to the place to fix the problem.

​
On previous versions, go to Run > Edit Configurations > Default > PHP
Remote Debug. Add or modify a server configuration for 10.11.12.14, and map
the project's root directory to /vagrant .

​

_I've enabled the phone and added ?XDEBUG_SESSION_START=cam_is_super_cool
to my url, but it doesn't pause execution!_
Double check inside your vagrant box that xdebug is loaded, or make sure
you're on a recent version of web-starter! xdebug has been included in the
default setup since I've been at Forum One, but I'm sure there are
prehistoric versions floating around.

_I'm debugging and I've changed the code, but it ignores my changes!_
Though it looks like you can edit the code as it's running, you can't... it
will keep running on the version of the file that was loaded into
memory.You'll have to refresh, or use "Evaluate expression" to mimic the
changes you're making in code as you go.

​

On Wed, Aug 12, 2015 at 8:20 PM, Derek Moon notifications@github.com
wrote:

> +1
> 
> On Wednesday, August 12, 2015, Keenan Holloway notifications@github.com
> wrote:
> 
> > It would be really helpful to have PhpStorm debug documentation about how
> > to debug this site or other Drupal sites in general using PhpStorm.
> > 
> > I know there have been links floating around but any in particular that
> > have worked fairly well and been helpful?
> > 
> > Thanks
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/forumone/web-starter/issues/108.
> 
> ## 
> 
> -- Sent from Mobile
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/forumone/web-starter/issues/108#issuecomment-130400216
> .

## 

Campbell Vertesi
Technical Architect

campbell@forumone.com
www.forumone.com
347.329.4511

**Comment by ohthehugemanatee** [comment]
fwiw
https://docs.google.com/document/d/1SewA_toVmsUPa5DLE6nbrE6xuFheD1X2w5DNSLHSuQE/edit

On Thu, Aug 13, 2015 at 2:34 PM, Campbell Vertesi cvertesi@forumone.com
wrote:

> Here's how you do it on one of our web-starter environments. I'm saving
> this as a blog post, btw. (stern looks all around)
> 
> 1) Tell PHPStorm to listen for incoming xdebug connections by clicking the
> little telephone icon in the top right corner.  It turns green.
> 
> ​
> 2) Mark a line as a "break point" by clicking beside the line number, to
> add a red dot. This is where PHPStorm will pause execution.
> 
> 3) In any web browser, visit a page on your local dev environment that
> should go past that break point. (actually that example is a bad one
> because it's a drush command) Add the parameter
> ?XDEBUG_SESSION_START=cam_is_muscular to the end of your URL. The value
> can really be anything, but that value in particular makes it better.
> 
> That's it! The page will stay "loading" and PHPStorm will steal focus from
> the browser to show you the debugger on that line. Below the code, you'll
> see the "debug pane", which shows all the variables in the environment as
> of that line. You can click into arrays and objects to see the value of
> everything you have available, even globals like $_GET!  On the left of the
> variables is a backtrace of "how it got here". You can click up to each
> level and see the current environment there, too.
> 
> ​
> You can use the pointy-clicky icons if you like, but you'll be stronger,
> healthier, happier, and more successful in life if you use the keyboard
> shortcuts:
> 
> _F8: Step over: *Go to the next line and pause there.
> *F7: Step into: *There's a function in the currently highlighted line.
> Step "into" that function and pause on the first line. If there are
> multiple functions, it will go through them one at a time.
> *shift+F7: Smart step into: *(PHPStorm 7 and up) like "step into", but
> offers you a choice of which function to step into on a line with multiple
> functions.
> *alt+F8: Evaluate expression: *Run some arbitrary code in the middle of
> execution. Find out what happens when you unset($_GET) partway through a
> request!
> *alt+F9: Run to cursor: *Run normally until wherever your cursor is
> situated.
> *cmd+alt+R: Resume:_ Resume running until you find another breakpoint, if
> any.
> 
> _NOTES AND TROUBLESHOOTING_
> 
> _Is there an easier way to start a debug session?_
> Why, yes! I'm glad you asked. Xdebug can also be triggered from a browser
> cookie. There are a ton of browser plugins that make it very convenient to
> trigger xdebug this way. I use The Easiest XDebug
> https://addons.mozilla.org/en-US/firefox/addon/the-easiest-xdebug/ for
> Firefox, but find one you like! Not that older versions of web-starter have
> a varnish configuration that filters out the Xdebug cookie, so either
> update web-starter or access your site directly through NGINX at
> http://localhost:8081/ .
> 
> _I'm getting weird errors about being unable to find a local path to
> somethingorother. What do I do?_
> The three things needed to get Xdebug working are: the browser has to
> trigger the server to start a connection, something needs to be listening
> for that connection, and it has to be able to relate paths on the server to
> paths on its' local copy. This is a problem with that third step. PHPStorm
> is getting a message like "I'm running /vagrant/public/index.php now, what
> line do you want me to stop on?" But it doesn't know where that is on your
> computer. You have to set up a mapping between paths on the vagrant box and
> paths on your own computer.
> 
> The error message in PHPStorm 9 links to the place to fix the problem.
> 
> ​
> On previous versions, go to Run > Edit Configurations > Default > PHP
> Remote Debug. Add or modify a server configuration for 10.11.12.14, and map
> the project's root directory to /vagrant .
> 
> ​
> 
> _I've enabled the phone and added ?XDEBUG_SESSION_START=cam_is_super_cool
> to my url, but it doesn't pause execution!_
> Double check inside your vagrant box that xdebug is loaded, or make sure
> you're on a recent version of web-starter! xdebug has been included in the
> default setup since I've been at Forum One, but I'm sure there are
> prehistoric versions floating around.
> 
> _I'm debugging and I've changed the code, but it ignores my changes!_
> Though it looks like you can edit the code as it's running, you can't...
> it will keep running on the version of the file that was loaded into
> memory.You'll have to refresh, or use "Evaluate expression" to mimic the
> changes you're making in code as you go.
> 
> ​
> 
> On Wed, Aug 12, 2015 at 8:20 PM, Derek Moon notifications@github.com
> wrote:
> 
> > +1
> > 
> > On Wednesday, August 12, 2015, Keenan Holloway notifications@github.com
> > wrote:
> > 
> > > It would be really helpful to have PhpStorm debug documentation about
> > > how
> > > to debug this site or other Drupal sites in general using PhpStorm.
> > > 
> > > I know there have been links floating around but any in particular that
> > > have worked fairly well and been helpful?
> > > 
> > > Thanks
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/forumone/web-starter/issues/108.
> > 
> > ## 
> > 
> > -- Sent from Mobile
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/forumone/web-starter/issues/108#issuecomment-130400216
> > .
> 
> ## 
> 
> Campbell Vertesi
> Technical Architect
> 
> campbell@forumone.com
> www.forumone.com
> 347.329.4511

## 

Campbell Vertesi
Technical Architect

campbell@forumone.com
www.forumone.com
347.329.4511

**Comment by wwhurley** [comment]
Converted Google Docs documentation to GitHub pages. See it at http://forumone.github.io/web-starter/localdev/debugging-phpstorm.html.
