### ISSUE TITLE
Update default Ruby version to 2.x

### ISSUE THREAD

**Issue by slucero** [forumone/web-starter#128]
Ruby version 2.x has been out and in regular use for a long time now. Maintaining the 1.9.x version as a dependency has introduced occasional issues like #127.

**Goal**: Update default Ruby version to use v2.x.

**Comment by wwhurley** [comment]
The changes coming from #22 include using rbenv at the system level which will likely resolve this issue. Have to see whether we want to backport this functionality to the Puppet provisioner we have currently.

**Comment by ohthehugemanatee** [comment]
Noting that I couldn't stand up a new VM because of this issue. I got.

```
Notice: /Stage[main]/Forumone::Ruby/Exec[vagrant bundle]/returns: Gem::InstallError: net-ssh requires Ruby version >= 2.0.
```

Easy enough to fix:

``` bash
$ rvm list

rvm rubies

=> ruby-1.9.3-p484 [ x86_64 ]
   ruby-2.0.0-p451 [ x86_64 ]
 * ruby-2.1.2 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

$ rvm current ruby-2.1.2
$ rvm uninstall ruby-1.9.3-p484

```

Then `vagrant provision` worked properly

On a side note, because El Capitan removed OSX's version of openssl, I also had to `brew link  --force openssl` to get things working with the homebrew version of openssl. That doesn't need an issue anywhere IMO, but i thought I'd leave this in case someone searches for it in the future.
