### ISSUE TITLE
Custom webroots are not working

### ISSUE THREAD

**Issue by johnbburg** [forumone/web-starter#266]
I noticed that custom webroots are not working for both the puppet and salt branches.

On puppet, it seems that just the webroot directory name is used, e.g. 

root htdocs;

instead of /vagrant/htdocs;

On salt, it just uses the default root "/vagrant/public"

**Comment by mshade** [comment]
It can be set in the salt branch, but I dont' think the generator asks you. Perhaps we should add that as a feature.

To set it to something else, copy the file at salt/roots/pillars/nginx/drupal.sls to something like custom.sls and edit the line that defines /vagrant/public to whatever you need. Then edit project.sls and tell it to use nginx.custom instead of nginx.drupal
