### ISSUE TITLE
"Query failed" on import

### ISSUE THREAD

**Issue by johnbburg** [forumone/web-starter#267]
This may be a issue more for documentation on a fix here than in resulting in any changes in web-starter. It only happened to me so far in the salt branch.

Importing database fails with the message: "Query failed"

This was in the log:

> 2017-02-14 18:21:25 5144 [ERROR] InnoDB: The total blob data length (2423515) is greater than 10% of the total redo log size (20971520). Please increase total redo log size.

Setting innodb_log_file_size=256M in /etc/my.cnf (defaulted to 10M in /etc/my.cnf.d) seems to resolve the issue.

**Comment by mshade** [comment]
Are you using the generator, or copying straight from salt branch of this repo? This is fixed inthe repo but I don't think the fix has been released in the generator yet. 

I believe it is due to a newer default version of MySQL where this setting is important. It was also fixed in NAR's project.sls if you want to take a look at that repo to see how it was done for a single project rather than in web starter defaults.

**Comment by johnbburg** [comment]
I'm using the generator.

**Comment by mshade** [comment]
Ok. I'll push to get another release of that out so this doesn't keep popping up.
