### ISSUE TITLE
Maintain Composer binary symlinks during deployment

### ISSUE THREAD

**Issue by arh1** [forumone/web-starter#275]
It'd be great to maintain the symlinks that Composer creates to its vendor binaries when we deploy to shared environments. That will let us, e.g., use Drupal Console via:

```[waapcd@dev public]$ ../vendor/bin/drupal list```

...instead of:

```[waapcd@dev public]$ ../vendor/drupal/console/bin/drupal list```

How to accomplish this, though? 

It looks like there's [some effort in the Composer community to re-install binaries](https://github.com/composer/composer/pull/5127) (ideally, it'd be a separate command than install/update). But presumably we don't want Composer to run at all on the target server (just on the build server).

Could Capistrano detect symlinks at ../vendor/bin and then recreate them on the target server (in drupal.rb)?

**Comment by arh1** [comment]
About Composer vendor binaries: https://getcomposer.org/doc/articles/vendor-binaries.md

**Comment by arh1** [comment]
See also #216

**Comment by coreylafferty** [comment]
@arh1 would that affect PC users since symlinks don't work in Windows?  Just ran into an issue on a project where we had to strip all the symlinks out because of that.

**Comment by mshade** [comment]
Corey - this is part of deployment rather than local build, so I don't think it'll have any impact on Windows users unless we start using Windows servers.

A simpler fix might just be to set a path or shell alias helper of some sort. It could do the path gymnastics for you. On the other hand, we don't need to go linking and copying everything that was part of the build that isn't needed to run the site. The eventual goal is something approaching immutable. You won't be SSH-ing in to do everything, you'll be doing another deploy. At least, in my mind...

**Comment by wwhurley** [comment]
This can be accomplished in the rsync settings. See https://github.com/forumone/generator-web-starter-capistrano/blob/master/web-starter/templates/config/deploy.rb#L37-L38.

**Comment by mshade** [comment]
Hmm - archive should already grab symlinks. What do you have in mind?

**Comment by wwhurley** [comment]
Those commands are run when rsyncing the files from the build server to the app server deployment staging directory (line 37) and then from the deployment staging directory to the deployment release directory (line 38). So if there is an issue with symlinks not being deployed it is due to one of those. I will say I have seen lines in the logs saying something along the lines of something not being a normal file and being skipped, or words to that effect.

**Comment by mshade** [comment]
Then '--archive' isn't being applied... I see the lines saying it's skipping non-regular file as well.

```
skipping non-regular file "public/themes/gesso_apcd/pattern-lab/vendor/bin/jsonlint"
skipping non-regular file "vendor/bin/drupal"
skipping non-regular file "vendor/bin/drush"
skipping non-regular file "vendor/bin/drush.complete.sh"
skipping non-regular file "vendor/bin/drush.launcher"
skipping non-regular file "vendor/bin/drush.php"
skipping non-regular file "vendor/bin/php-parse"
skipping non-regular file "vendor/bin/psysh"
skipping non-regular file "vendor/zendframework/zend-escaper/doc/book/index.md"
skipping non-regular file "vendor/zendframework/zend-feed/doc/book/index.md"
skipping non-regular file "vendor/zendframework/zend-stdlib/doc/book/index.md"
  INFO [d8ae6d24] Running rsync --archive --acls --xattrs "/var/www/vhosts/waapcd.dev/shared/deploy/" "/var/www/vhosts/waapcd.dev/releases/20170505060323/" as waapcd@dev.forumone.com
 DEBUG [d8ae6d24] Command: rsync --archive --acls --xattrs "/var/www/vhosts/waapcd.dev/shared/deploy/" 
```

I believe --archive is only being applied to the ./shared/deploy -> releases rsync command. Hmm, how can we get the command/output from the actual initial push to the server?

**Comment by wwhurley** [comment]
The command is what's shown on https://github.com/forumone/generator-web-starter-capistrano/blob/master/web-starter/templates/config/deploy.rb#L37. The output is where you're seein ghte "skipping non-regular file." I believe I omitted the `--archive` flag because of permissions issues. It's been a while, though, so I'm not entirely sure.

**Comment by mshade** [comment]
@arh1 Try prepending --archive to the arguments in line 37 on WA-APCD if you would like to try this solution on that project:

https://github.com/forumone/OHSU-WA-APCD-web/blob/master/config/deploy.rb#L37

**Comment by arh1** [comment]
Cool, that worked, Mike:
https://jenkins.forumone.com/job/WA-APCD/job/WA-APCD-dev/90/console

PR created, but as referenced there...

> I believe I omitted the --archive flag because of permissions issues. It's been a while, though, so I'm not entirely sure.

Not sure if this warrants further discussion.
