### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by johnbburg** [forumone/web-starter#52]
Access sites via https is missing in web starter the current workaround is to disable https entirely. However, this can lead to overlooking issues like blocked mixed content requests and leading to errors.

Add support for SSL and https to the web starter package.

**Comment by johnbburg** [comment]
I am looking into setting up SSL on a VM to address a specific bug in a project. I know how to setup SSL directly on the webserver (apache in this case), but I'm not sure on how to set this up through the provisioning process. So I'm just looking for some direction on where to go for this.

Also, I'm not sure how to manage the port forwarding. SSL seems to work from within the vm, but even If I forward 443 to 8443, I can't access it from the host. Also switching between these ports on the front end will be cludgy without any form of forwarding on the host OS (something like http://www.openbsd.org/faq/pf/rdr.html).

**Comment by ohthehugemanatee** [comment]
I have a working solution.

It requires merging the work from #82 into your web-starter (to generate the certs), and the work from https://github.com/forumone/puppet-forumone/issues/6 into your puppet-forumone repository (to add SSL configs for NGINX/HTTPD).

These two patches need review, probably from @wwhurley personally since it's two interdependent projects at once.

**Comment by ohthehugemanatee** [comment]
This doesn't require any change to web-starter. It's already working with a change to puppet-forumone. See pull request: https://github.com/forumone/puppet-forumone/pull/7

Closing this issue.
