### ISSUE TITLE
local.settings.php for local development

### ISSUE THREAD

**Issue by lrobeson** [forumone/web-starter#66]
**Problem:**
Every developer has their own preferred tools/settings for local development, but there's currently no "approved" way (that I'm aware of) to make those modifications.

I understand environment consistency is one of the main reasons for using Web Starter Kit, but I think it's important to allow for this kind of personalization because familiarity and little tweaks make for happier developers.

**Proposed solution:**
I add this to settings.php in my projects (copied from http://www.thirdandgrove.com/the-drupal-settings-file-done-right):

```
/**
 * Settings file for local development only.
 *
 * This file should NEVER be committed to version control and should never exist
 * on a non-local development machine.
 */
if (file_exists('./' . conf_path() . '/local.settings.php')) {
  require './' . conf_path() . '/local.settings.php';
}
```

That allows me to use a local.settings.php file which contains my preferred local configuration:

```
<?php

  # change site name
  $conf['site_name'] = 'EDGE LOCAL';

  # turn off caching &amp; aggregation
  $conf['cache'] = FALSE;
  $conf['block_cache'] = FALSE;
  $conf['preprocess_css'] = FALSE;
  $conf['preprocess_js'] = FALSE;

  # display all error messages
  $conf['error_level'] = 1;
  ini_set('display_errors', TRUE);
  ini_set('display_startup_errors', TRUE);

?>
```

**Comment by arh1** [comment]
settings.vm.php should be in the repo, and copied to settings.php via the post provisioner at the end of the Vagrant setup.  Is there a reason not to use that file over a separate local.settings.php file?

**Comment by lrobeson** [comment]
But because settings.vm.php is in the repo any changes to it are gonna show up in git status and get in the way every time you try to update.

**Comment by arh1** [comment]
settings.vm.php is just a template that'll be copied in place upon initial setup of the VM, whereas settings.php is the file that Drupal's actually reading in your VM.

So changes to settings.vm.php can be committed when they're appropriate for all devs on the project (but you'd need to let the other devs know, so they can manually apply the changes to settings.php ). And otherwise, you can make configuration changes that are unique to your environment in settings.php and the file will be gitignore'd .

**Comment by lrobeson** [comment]
Okay I must be working on a project that doesn't follow this setup because when I make changes to settings.php it gets copied to vm.settings.php immediately and then Git complains about the changes. I'll mention this to the project Dev.

**Comment by slucero** [comment]
The default provisioning script only symlinks `settings.php` to `settings.vm.php`, so any edits you made to `settings.php` would actually be applied to `settings.vm.php`. A work-around to this for you might be to delete the `settings.php` symlink after it has run and manually copy `settings.vm.php` over it. From that point since it’s an independent file the changes shouldn’t be reflected by git. Note that this does break the linkage to `settings.vm.php` though, so from that point forward you would be in charge of making sure you keep those synced up.

That being said, I’m a fan of this request as well since it does take care of that pain point of using personalized settings that aren’t relevant to everyone on the project.

**Comment by wwhurley** [comment]
We generally don't recommend symlinks due to problems with them on Windows platforms.

**Comment by wwhurley** [comment]
In order to be consistent we've made the naming convention settings.local.php. Note that this change was made to the example settings.vm.php file only and would need to be applied manually to any extant project. That file is in /examples/drupal/settings.vm.php

**Comment by ohthehugemanatee** [comment]
... and now we're COPYING instead of symlinking to settings.php, right?

**Comment by wwhurley** [comment]
The settings.vm.php is copied to settings.php by the example Drupal custom post-process shell provisioner. Symlinks could be used instead on a particular user's machine, but given issues with Windows machines and symlinks within shared folders we can't really support that universally.
