### ISSUE TITLE
Establish a system for versioning box images

### ISSUE THREAD

**Issue by azinck** [forumone/web-starter#90]
Currently, once you download the forumone/centos64-64 box you'll never get a newer version of that image, if it ever gets updated.  

If boxes are always backwards-compatible with previous versions of web-starter then I think you could just update the box name in the web-starter whenever a new box image is uploaded with functionality on which you depend, but maintaining that sort of backwards-compatibility seems unreasonable/impossible. 

Instead it would seem that both the files and the box names need to adhere to some sort of versioning so that we can ensure folks get an image that's compatible with the version of web-starter they're running.

**Comment by wwhurley** [comment]
The box is discoverable on Atlas and the system does support versioning -- see https://atlas.hashicorp.com/forumone/boxes/centos64-64. Note that at present this is unused since we haven't gotten back to automating the creation of the boxes using Packer, so we haven't actually released any new revisions.

**Comment by azinck** [comment]
So does it change the filename when a new version is created?
